version: '3'
services:
  api_gateway-service:
    build: ./api_gateway-service
    ports:
      - "3010:3010"    
    depends_on:
      - users-service
      - pets-service
      - posts-service
      - autentication-service

  users-service:
    build: ./users-service
    ports:
      - "6010:6010"
    environment:
      - MONGO_URI=mongodb://mongo-users:27017/bd_users
    depends_on:
      - mongo-users

  pets-service:
    build: ./pets-service
    ports:
      - "6020:6020"
    environment:
      - MONGO_URI=mongodb://mongo-pets:27017/bd_posts
    depends_on:
      - mongo-pets

  posts-service:
    build: ./posts-service
    ports:
      - "6030:6030"
    environment:
      - MONGO_URI=mongodb://mongo-posts:27017/bd_posts_
    depends_on:
      - mongo-posts

  autentication-service:
    build: ./autentication-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo-users:27017/bd_users
      - API_GATEWAY_URL=http://api_gateway-service:3010
    depends_on:
      - mongo-users

  mongo-users:
    image: mongo
    volumes:
      - mongodb_users_data:/data/db

  mongo-pets:
    image: mongo
    volumes:
      - mongodb_pets_data:/data/db

  mongo-posts:
    image: mongo
    volumes:
      - mongodb_posts_data:/data/db

volumes:
  mongodb_users_data:
  mongodb_pets_data:
  mongodb_posts_data:

networks:
  default:
    driver: bridge